(function() {var implementors = {};
implementors["num"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"num/bigint/enum.ParseBigIntError.html\" title=\"enum num::bigint::ParseBigIntError\">ParseBigIntError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"num/rational/struct.ParseRatioError.html\" title=\"struct num::rational::ParseRatioError\">ParseRatioError</a>",];
implementors["rustc_serialize"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"rustc_serialize/base64/enum.FromBase64Error.html\" title=\"enum rustc_serialize::base64::FromBase64Error\">FromBase64Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"rustc_serialize/hex/enum.FromHexError.html\" title=\"enum rustc_serialize::hex::FromHexError\">FromHexError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">StdError</a> for <a class=\"enum\" href=\"rustc_serialize/json/enum.DecoderError.html\" title=\"enum rustc_serialize::json::DecoderError\">DecoderError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">StdError</a> for <a class=\"enum\" href=\"rustc_serialize/json/enum.ParserError.html\" title=\"enum rustc_serialize::json::ParserError\">ParserError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">StdError</a> for <a class=\"enum\" href=\"rustc_serialize/json/enum.EncoderError.html\" title=\"enum rustc_serialize::json::EncoderError\">EncoderError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
